#pragma config(Sensor, in1,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  liftLimit,      sensorTouch)
#pragma config(Motor,  port2,           driveRight13,  tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           driveRight2,   tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           driveLeft13,   tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           driveLeft2,    tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           rightLift,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           leftLift,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task leftDrive();
task rightDrive();
task lift();
task debug();
task flip();
int liftState = 0; //0=Down, 1=Low, 2=High
bool flip = false; // false means not flipped yet, true means flipped

task main() {
	startTask (leftDrive);
	startTask (rightDrive);
	startTask (lift);
	startTask (debug);
	while(true) {
		wait1Msec(1);
	}
}
task debug() {
	while(true) {
		clearLCDLine(1);
		displayLCDNumber(1, 1, SensorValue(liftPot));
		displayLCDNumber(1, 6, liftState);
		wait1Msec(100);
	}
}
task flip() {
	while(true)	{
		//flipper code	
	}
task lift() {
	while(true) {
		if(vexRT[Btn6U] == 1) {												//High Post
			motor[rightLift] = 127;
			motor[leftLift] = 127;
			while(SensorValue(liftPot) > 2100) {
				wait1Msec(1);
			}
			motor[rightLift] = 0;
			motor[leftLift] = 0;
			liftState = 2;
		}
		else if(vexRT[Btn6D] == 1) {									//Low Post
			motor[rightLift] = 127;
			motor[leftLift] = 127;
			while(SensorValue(liftPot) > 3100) {
				wait1Msec(1);
			}
			motor[rightLift] = 0;
			motor[leftLift] = 0;
			liftState = 1;
		}
		else if(vexRT[Btn5U] == 1 & liftState != 0) {	//Lower cap onto post
			motor[rightLift] = -127;
			motor[leftLift] = -127;
			while(SensorValue(liftPot) < 5) {						//Set the value to correct amount
				wait1Msec(1);
			}
			motor[rightLift] = 0;
			motor[leftLift] = 0;
		}
		else if(vexRT[Btn5D] == 1 & liftState != 0) {	//Put lift to down position
			motor[rightLift] = -127;
			motor[leftLift] = -127;
			while(SensorValue(liftLimit) == 0) {
				wait1Msec(1);
			}
			motor[rightLift] = 0;
			motor[leftLift] = 0;
			liftState = 0;
		}
		wait1Msec(1);
	}
}
task leftDrive() {
	while (true) {
		if (abs(vexRT[Ch3]) <= 20) {					//error
			motor[driveLeft13] = 0;
			motor[driveLeft2] = 0;
		}
		else if (abs(vexRT[Ch3]) <= 62) {		//low speed
			if (vexRT[Ch2] < 0) {	//Reverse
				motor[driveLeft13] = -43;
				motor[driveLeft2] = -43;
			}
			else {								//Forward
				motor[driveLeft13] = 43;
				motor[driveLeft2] = 43;
			}
		}
		else if (abs(vexRT[Ch3]) <= 90) {		//mid speed
			if (vexRT[Ch2] < 0) {	//Reverse
				motor[driveLeft13] = -85;
				motor[driveLeft2] = -85;
			}
			else {								//Forward
				motor[driveLeft13] = 85;
				motor[driveLeft2] = 85;
			}
		}
		else {															//high speed
			if (vexRT[Ch3] < 0) {	//Reverse
				motor[driveLeft13] = -127;
				motor[driveLeft2] = -127;
			}
			else {								//Forward
				motor[driveLeft13] = 127;
				motor[driveLeft2] = 127;
			}
		}
		wait1Msec(1);
	}
}
task rightDrive() {
	while (true) {
		if (abs(vexRT[Ch2]) <= 20) {					//error
			motor[driveRight13] = 0;
			motor[driveRight2] = 0;
		}
		else if (abs(vexRT[Ch2]) <= 62) {		//low speed
			if (vexRT[Ch2] < 0) {	//Reverse
				motor[driveRight13] = -43;
				motor[driveRight2] = -43;
			}
			else {								//Forward
				motor[driveRight13] = 43;
				motor[driveRight2] = 43;
			}
		}
		else if (abs(vexRT[Ch2]) <= 90) {		//mid speed
			if (vexRT[Ch2] < 0) {	//Reverse
				motor[driveRight13] = -85;
				motor[driveRight2] = -85;
			}
			else {								//Forward
				motor[driveRight13] = 85;
				motor[driveRight2] = 85;
			}
		}
		else {															//high speed
			if (vexRT[Ch2] < 0) {	//Reverse
				motor[driveRight13] = -127;
				motor[driveRight2] = -127;
			}
			else {								//Forward
				motor[driveRight13] = 127;
				motor[driveRight2] = 127;
			}
		}
		wait1Msec(1);
	}
}
